alias config-txt='sudo nano /boot/firmware/config.txt'
alias cmdline-txt='sudo nano /boot/firmware/cmdline.txt'
alias tty1-config='sudo systemctl edit getty@tty1'
alias tty2-config='sudo systemctl edit getty@tty2'
alias tty-reload='sudo systemctl daemon-reload && sudo systemctl restart getty@tty1 getty@tty2'